### ISSUE TITLE
Unable to start training bot

### ISSUE THREAD

**Issue by MukhamejanKaratayev** [ilcardella/TradingBot#358]
Hello. Thanks for sharing this project. I was trying to run it, but I have a problem. I followed all steps, created a `.credentials` file and etc. However, when I try to run it will `trading_bot` command I have the following error:
`Traceback (most recent call last):
  File "/home/mukhameajn/.local/bin/trading_bot", line 8, in <module>
    sys.exit(main())
  File "/home/mukhameajn/.local/lib/python3.7/site-packages/tradingbot/__init__.py", line 70, in main
    bot = TradingBot(time_provider=TimeProvider(), config_filepath=args.config)
  File "/home/mukhameajn/.local/lib/python3.7/site-packages/tradingbot/trading_bot.py", line 47, in __init__
    self.config = Configuration.from_filepath(config_filepath)
  File "/home/mukhameajn/.local/lib/python3.7/site-packages/tradingbot/components/configuration.py", line 31, in from_filepath
    with filepath.open(mode="r") as f:
  File "/home/mukhameajn/anaconda3/lib/python3.7/pathlib.py", line 1208, in open
    opener=self._opener)
IsADirectoryError: [Errno 21] Is a directory: '.'`

**Comment by dojo90** [comment]
```yaml
version: '2'
services:
  TradingBot:
    image: ilcardella/tradingbot:latest
    container_name: TradingBot
    volumes:
      - /docker/TradingBot/config/trading_bot.toml:/root/.TradingBot/config/trading_bot.toml
      - /docker/TradingBot/config/.credentials:/root/.TradingBot/config/.credentials
      - /docker/TradingBot/logs:/root/.TradingBot/log      
```

```yaml
version: '2'
services:
  TradingBot:
    image: ilcardella/tradingbot:latest
    container_name: TradingBot
    volumes:
      - /docker/TradingBot/config/trading_bot.toml:/.TradingBot/config/trading_bot.toml
      - /docker/TradingBot/config/.credentials:/.TradingBot/config/.credentials
      - /docker/TradingBot/logs:/.TradingBot/log      
```

I'm stuck because I don't know what the problem is here. The container is started as root.
